version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'
    cooldown:
      default-days: 7
