name: 'Set up PHP Action'
author: shivammathur
description: 'GitHub Action for PHP'
branding:
  color: 'purple'
  icon: 'play-circle'
inputs:
  php-version:
    description: 'Set up PHP version.'
    default: '8.1'
    required: true
  extensions:
    description: 'Set up PHP extensions.'
    required: false
  ini-file:
    description: 'Set base ini file.'
    default: 'production'
    required: false
  ini-values:
    description: 'Add values to php.ini.'
    required: false
  coverage:
    description: 'Set up code coverage driver.'
    required: false
  tools:
    description: 'Set up popular tools globally.'
    required: false
outputs:
  php-version:
    description: 'PHP version in semver format'
runs:
  using: 'node16'
  main: 'dist/index.js'
