name: 'Setup PHP Action'
author: shivammathur
description: 'Setup a PHP environment with composer and add it to the PATH'
branding:
  icon: 'activity'  
  color: 'purple'
inputs:
  php-version:
    description: 'PHP version to be installed.'
    required: true
  extension-csv:
    description: '(Optional) Comma seperated list of PHP extensions to be installed.'
    required: false
  ini-values-csv: 
    description: '(Optional) Custom values you want to set in php.ini'
    required: false
runs:
  using: 'node12'
  main: 'lib/install.js'
