name: Testing Yii2 with PostgreSQL
on: [push, pull_request]
jobs:
  laravel:
    name: Yii2 (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      TEST_DB_USERNAME: postgres
      TEST_DB_PASSWORD: postgres
      DB_CHARSET: utf8
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set Node.js 10.x
        uses: actions/setup-node@master
        with:
          version: 10.x
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@master #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: mbstring, intl, gd, imagick, zip, dom, pgsql
          coverage: xdebug #optional
      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Prepare the application
        run: |
          php -r "file_exists('.env') || copy('.env.dist', '.env');"
          php console/yii app/setup
          npm install --development
          npm run build
        env:
          DB_DSN: pgsql:host=127.0.0.1;port=${{ job.services.postgres.ports['5432'] }};dbname=postgres
          TEST_DB_DSN: pgsql:host=127.0.0.1;port=${{ job.services.postgres.ports['5432'] }};dbname=postgres
      - name: Run Tests
        run: |
          vendor/bin/codecept build
          php tests/bin/yii app/setup --interactive=0
          nohup php -S localhost:8080 > yii.log 2>&1 &
          vendor/bin/codecept run
        env:
          DB_DSN: pgsql:host=127.0.0.1;port=${{ job.services.postgres.ports['5432'] }};dbname=postgres
          TEST_DB_DSN: pgsql:host=127.0.0.1;port=${{ job.services.postgres.ports['5432'] }};dbname=postgres